CREATE TABLE [flowdb].[dbo].[users] (
  [id] int IDENTITY(1,1) NOT NULL,
  [username] nvarchar(100) NOT NULL,
  [employee_number] nvarchar(50),
  [email] nvarchar(255),
  [display_name] nvarchar(255),
  [first_name] nvarchar(100),
  [last_name] nvarchar(100),
  [department] nvarchar(255),
  [title] nvarchar(255),
  [auth_source] nvarchar(20) NOT NULL,
  [password_hash] nvarchar(500),
  [is_active] bit NOT NULL DEFAULT ((1)),
  [is_locked] bit NOT NULL DEFAULT ((0)),
  [last_login_at] datetime2,
  [created_at] datetime2 NOT NULL DEFAULT (getutcdate()),
  [created_by] nvarchar(100),
  [updated_at] datetime2,
  [updated_by] nvarchar(100),
  [supervisor_emp_no] nvarchar(50),
  [manager_emp_no] nvarchar(50),
  [director_emp_no] nvarchar(50),
  PRIMARY KEY ([id])
);