CREATE TABLE [flowdb].[dbo].[workflow_report_configs] (
  [id] int IDENTITY(1,1) NOT NULL,
  [workflow_id] nvarchar(50) NOT NULL,
  [name] nvarchar(200) NOT NULL,
  [description] nvarchar(500),
  [columns_json] nvarchar(-0.5) NOT NULL,
  [created_by] nvarchar(200),
  [created_at] datetime2 NOT NULL,
  [updated_at] datetime2 NOT NULL,
  [date_range_type] nvarchar(30) NOT NULL,
  [custom_from] datetime2,
  [custom_to] datetime2,
  [rolling_days] int,
  [default_status] nvarchar(30),
  [is_scheduled] bit NOT NULL,
  [schedule_type] nvarchar(20),
  [schedule_time] nvarchar(5),
  [schedule_day_of_week] int,
  [schedule_day_of_month] int,
  [is_active] bit NOT NULL,
  [filters_json] nvarchar(-0.5),
  [cron_expression] nvarchar(100),
  [schedule_times_json] nvarchar(200),
  [schedule_days_of_week_json] nvarchar(50),
  [schedule_days_of_month_json] nvarchar(100),
  [recipients_json] nvarchar(-0.5),
  [output_format] nvarchar(10) NOT NULL,
  [filter_schema_json] nvarchar(-0.5),
  [schedule_email_subject] nvarchar(300),
  PRIMARY KEY ([id])
);